BABEL_DEFAULT_LOCALE = "en_GB"

HOME_URL = "https://docs.metea.org.uk/"
HOME_TITLE = "Mathematics Education"
FLASK_APP = "wsgi.py"
FLASK_DEBUG = 0

[kerko.meta]

title = "Evidence Library – Mathematics Education"
google_analytics_id = "UA-169419325-2"

[kerko.link_groups]

[[kerko.link_groups.breadcrumb_base]]
text = "Mathematics Education"
type = "url"
url = "https://docs.metea.org.uk/"

[[kerko.link_groups.breadcrumb_base]]
text = "Evidence Library"
type = "endpoint"
endpoint = "kerko.search"

[kerko.features]

download_attachment_new_window = true
open_in_zotero_app = true
open_in_zotero_web = true
print_item = true
print_results = true
results_abstracts = true
results_abstracts_max_length = 500
results_abstracts_max_length_leeway = 40
relations_initial_limit = 50

[kerko.search]

result_fields = ["id", "attachments", "bib", "data", "preview", "url"]
whoosh_language = "en"

[kerko.templates]

layout = "kerkoapp/layout.html.jinja2"
search = "kerkoapp/search.html.jinja2"
search_item = "kerkoapp/search-item.html.jinja2"
item = "kerkoapp/item.html.jinja2"

[kerko.zotero]

locale = "en-GB"

# CAUTION: The URL's query string (after the '?') must be changed after any edit
# to the CSL style, otherwise zotero.org might still use a previously cached
# version of the file.
csl_style = "https://docs.opendeved.net/static/dist/csl/eth_apa.xml?202012301815"
batch_size = 20

item_exclude_re = "^_exclude$"

child_include_re = "^(_publish)|(publishPDF)$"
child_exclude_re = ""

[kerko.facets]

[kerko.facets.tag]
enabled = false

[kerko.facets.link]
enabled = false

[kerko.facets.item_type]
enabled = false

[kerko.facets.featured]
enabled = true
type = "collection"
collection_key = "VQ8AKG3J"
filter_key = "featured"
title = "Country"
weight = 10
initial_limit = 15
initial_limit_leeway = 5


[kerko.performance]

whoosh_index_memory_limit = 64

[kerkoapp.proxy_fix]

enabled = false
x_for = 1
x_proto = 1
x_host = 0
x_port = 0
x_prefix = 0
